// Fake but plausible data for the BizBoost Command Centre
// Irish SMB clients an agency would have

window.BIZBOOST_DATA = (() => {
  const clients = [
    {
      id: "tobin-tiling",
      name: "Tobin Tiling & Stone",
      handle: "tobintiling.ie",
      city: "Ennis",
      niche: "Tiling",
      plan: "Domination",
      mrr: 998,
      since: "Jun 2026",
      onboarded: 2,
      health: 70,
      owner: "Gerry Tobin",
      avatar: "T",
      color: "#4FE3C1",
      leads30: 0,
      leadsΔ: 0,
      bookings30: 0,
      bookingsΔ: 0,
      revenue30: 0,
      revenueΔ: 0,
      roas: 0,
      missedCalls: 0,
      reviews: { count: 0, rating: 0, new30: 0 },
      adSpend: 0,
      website: { visits30: 0, visitsΔ: 0, conv: 0 },
      followers: { ig: 0, fb: 0, tt: 0 },
      pendingTasks: 5,
      lastTouch: "today",
      nextDue: "Onboarding",
      flag: "Onboarding",
      services: ["Bathroom tiling", "Natural stone", "Wet rooms"],
      sparkline: [0, 0, 0, 0, 0],
      onboarding: { active: true, done: ["k1", "k2"], started: "2 days ago" },
      connected: ["meta", "gbp"],
      memory: {
        why: "20 years on the tools, obsessive about a clean grout line — does the jobs cowboys won't touch.",
        ideal: "Full bathroom & wet-room renovations for homeowners who care about finish, €6k+ jobs.",
        vibe: "Premium & clean",
        competitor: "Clare Tile Co"
      }
    },
    {
      id: "murphy-plumbing",
      name: "Murphy & Sons Plumbing",
      handle: "murphyplumbing.ie",
      city: "Galway",
      niche: "Plumbing",
      plan: "Domination",
      mrr: 998,
      since: "Jan 2026",
      onboarded: 142, // days
      health: 92,
      owner: "Liam Murphy",
      avatar: "M",
      color: "#3FE0A8",
      leads30: 47,
      leadsΔ: 0.32,
      bookings30: 31,
      bookingsΔ: 0.18,
      revenue30: 28400,
      revenueΔ: 0.21,
      roas: 6.4,
      missedCalls: 2,
      reviews: { count: 187, rating: 4.9, new30: 22 },
      adSpend: 2400,
      website: { visits30: 8120, visitsΔ: 0.41, conv: 4.2 },
      followers: { ig: 2840, fb: 1620, tt: 0 },
      pendingTasks: 3,
      lastTouch: "2h ago",
      nextDue: "Weekly call · Thu",
      flag: null,
      services: ["Emergency callouts", "Boiler install", "Bathroom fitouts"],
      sparkline: [12, 14, 11, 18, 21, 19, 24, 22, 26, 29, 31, 35, 38, 41, 47]
    },
    {
      id: "coastal-roofing",
      name: "Coastal Roofing Ltd",
      handle: "coastalroofing.ie",
      city: "Cork",
      niche: "Roofing",
      plan: "Domination",
      mrr: 998,
      since: "Nov 2025",
      onboarded: 198,
      health: 88,
      owner: "Declan Walsh",
      avatar: "C",
      color: "#CFFF3A",
      leads30: 39,
      leadsΔ: 0.12,
      bookings30: 22,
      bookingsΔ: 0.04,
      revenue30: 41200,
      revenueΔ: 0.09,
      roas: 5.1,
      missedCalls: 0,
      reviews: { count: 96, rating: 4.8, new30: 11 },
      adSpend: 3100,
      website: { visits30: 5240, visitsΔ: 0.18, conv: 5.8 },
      followers: { ig: 1840, fb: 2210, tt: 410 },
      pendingTasks: 1,
      lastTouch: "yesterday",
      nextDue: "Content batch · Mon",
      flag: null,
      services: ["Slate roofing", "Flat roofs", "Gutter repair"],
      sparkline: [22, 26, 24, 28, 31, 29, 33, 30, 34, 32, 35, 38, 36, 39, 39]
    },
    {
      id: "kelly-detailing",
      name: "Kelly Auto Detailing",
      handle: "kellydetailing.ie",
      city: "Dublin",
      niche: "Auto Detailing",
      plan: "Growth",
      mrr: 698,
      since: "Mar 2026",
      onboarded: 78,
      health: 71,
      owner: "Aoife Kelly",
      avatar: "K",
      color: "#FFB547",
      leads30: 84,
      leadsΔ: 0.58,
      bookings30: 51,
      bookingsΔ: 0.44,
      revenue30: 16800,
      revenueΔ: 0.39,
      roas: 4.2,
      missedCalls: 5,
      reviews: { count: 64, rating: 4.7, new30: 18 },
      adSpend: 1800,
      website: { visits30: 11200, visitsΔ: 0.62, conv: 3.1 },
      followers: { ig: 6210, fb: 980, tt: 14200 },
      pendingTasks: 6,
      lastTouch: "3d ago",
      nextDue: "Ads review · today",
      flag: "Needs ad approval",
      services: ["Full detail", "Ceramic coating", "Headlight restoration"],
      sparkline: [18, 22, 31, 28, 36, 42, 48, 51, 58, 63, 68, 72, 76, 80, 84]
    },
    {
      id: "burke-landscaping",
      name: "Burke Landscaping",
      handle: "burkelandscapes.ie",
      city: "Limerick",
      niche: "Landscaping",
      plan: "Growth",
      mrr: 698,
      since: "Feb 2026",
      onboarded: 102,
      health: 84,
      owner: "Seán Burke",
      avatar: "B",
      color: "#4FE3C1",
      leads30: 28,
      leadsΔ: 0.08,
      bookings30: 19,
      bookingsΔ: 0.11,
      revenue30: 22600,
      revenueΔ: 0.14,
      roas: 5.8,
      missedCalls: 1,
      reviews: { count: 41, rating: 4.9, new30: 8 },
      adSpend: 1200,
      website: { visits30: 3210, visitsΔ: 0.09, conv: 4.8 },
      followers: { ig: 1240, fb: 760, tt: 0 },
      pendingTasks: 2,
      lastTouch: "5h ago",
      nextDue: "Review request batch",
      flag: null,
      services: ["Garden design", "Turf laying", "Maintenance"],
      sparkline: [18, 19, 22, 20, 24, 23, 26, 24, 27, 25, 28, 26, 29, 27, 28]
    },
    {
      id: "boyne-joinery",
      name: "Boyne Valley Joinery",
      handle: "boynejoinery.ie",
      city: "Drogheda",
      niche: "Joinery",
      plan: "Starter",
      mrr: 0,
      since: "Apr 2026",
      onboarded: 41,
      health: 64,
      owner: "Tomás Reilly",
      avatar: "B",
      color: "#8B7CFF",
      leads30: 14,
      leadsΔ: -0.04,
      bookings30: 9,
      bookingsΔ: 0.02,
      revenue30: 11400,
      revenueΔ: 0.06,
      roas: 3.8,
      missedCalls: 3,
      reviews: { count: 22, rating: 4.6, new30: 4 },
      adSpend: 600,
      website: { visits30: 1840, visitsΔ: -0.02, conv: 3.4 },
      followers: { ig: 480, fb: 320, tt: 0 },
      pendingTasks: 4,
      lastTouch: "6d ago",
      nextDue: "Upsell call · Wed",
      flag: "Upsell opportunity",
      services: ["Bespoke kitchens", "Staircases", "Wardrobes"]
    },
    {
      id: "osullivan-electrical",
      name: "O'Sullivan Electrical",
      handle: "osullivanelectric.ie",
      city: "Waterford",
      niche: "Electrical",
      plan: "Domination",
      mrr: 998,
      since: "Sep 2025",
      onboarded: 248,
      health: 95,
      owner: "Mick O'Sullivan",
      avatar: "O",
      color: "#FF7A8A",
      leads30: 61,
      leadsΔ: 0.22,
      bookings30: 44,
      bookingsΔ: 0.19,
      revenue30: 38200,
      revenueΔ: 0.16,
      roas: 7.2,
      missedCalls: 0,
      reviews: { count: 312, rating: 4.95, new30: 28 },
      adSpend: 2200,
      website: { visits30: 9420, visitsΔ: 0.24, conv: 5.4 },
      followers: { ig: 1980, fb: 3400, tt: 0 },
      pendingTasks: 0,
      lastTouch: "today",
      nextDue: "QBR · next Tue",
      flag: "Top performer",
      services: ["EV chargers", "Rewiring", "Commercial fitouts"]
    },
    {
      id: "atlantic-dental",
      name: "Atlantic Dental Clinic",
      handle: "atlanticdental.ie",
      city: "Sligo",
      niche: "Dental",
      plan: "Domination",
      mrr: 998,
      since: "Dec 2025",
      onboarded: 168,
      health: 81,
      owner: "Dr. Niamh O'Connor",
      avatar: "A",
      color: "#5BCEFA",
      leads30: 52,
      leadsΔ: 0.14,
      bookings30: 38,
      bookingsΔ: 0.21,
      revenue30: 47800,
      revenueΔ: 0.12,
      roas: 5.6,
      missedCalls: 1,
      reviews: { count: 142, rating: 4.85, new30: 14 },
      adSpend: 2800,
      website: { visits30: 6420, visitsΔ: 0.07, conv: 5.1 },
      followers: { ig: 3210, fb: 1820, tt: 0 },
      pendingTasks: 2,
      lastTouch: "1d ago",
      nextDue: "Campaign launch · Fri",
      flag: null,
      services: ["Invisalign", "Implants", "Hygiene"]
    },
    {
      id: "greenway-fitness",
      name: "Greenway Fitness",
      handle: "greenwayfit.ie",
      city: "Kildare",
      niche: "Fitness Studio",
      plan: "Growth",
      mrr: 698,
      since: "Feb 2026",
      onboarded: 108,
      health: 58,
      owner: "Conor Doyle",
      avatar: "G",
      color: "#FF6B5C",
      leads30: 22,
      leadsΔ: -0.18,
      bookings30: 11,
      bookingsΔ: -0.24,
      revenue30: 7400,
      revenueΔ: -0.12,
      roas: 2.4,
      missedCalls: 7,
      reviews: { count: 38, rating: 4.5, new30: 2 },
      adSpend: 1400,
      website: { visits30: 4210, visitsΔ: -0.08, conv: 2.1 },
      followers: { ig: 1820, fb: 410, tt: 980 },
      pendingTasks: 8,
      lastTouch: "8d ago",
      nextDue: "Retention call · today",
      flag: "At risk",
      services: ["6-week challenge", "Personal training", "Group classes"]
    },
    {
      id: "riverside-cafe",
      name: "Riverside Café",
      handle: "riversidecafe.ie",
      city: "Kilkenny",
      niche: "Hospitality",
      plan: "Growth",
      mrr: 698,
      since: "Mar 2026",
      onboarded: 84,
      health: 78,
      owner: "Orla Hennessy",
      avatar: "R",
      color: "#FFD66B",
      leads30: 38,
      leadsΔ: 0.28,
      bookings30: 0,
      bookingsΔ: 0,
      revenue30: 18900,
      revenueΔ: 0.18,
      roas: 0,
      missedCalls: 0,
      reviews: { count: 218, rating: 4.7, new30: 32 },
      adSpend: 800,
      website: { visits30: 7820, visitsΔ: 0.34, conv: 0 },
      followers: { ig: 8420, fb: 2240, tt: 4120 },
      pendingTasks: 2,
      lastTouch: "today",
      nextDue: "Content batch · Thu",
      flag: null,
      services: ["Brunch", "Events", "Private hire"]
    }
  ];

  const tasks = [
    { id: "t1", title: "Approve Q4 ad creative — Kelly Detailing", client: "kelly-detailing", due: "Today", priority: "P0", status: "doing", category: "Ads", assignee: "Bartek" },
    { id: "t2", title: "Greenway Fitness retention call", client: "greenway-fitness", due: "Today", priority: "P0", status: "todo", category: "Account", assignee: "Bartek" },
    { id: "t3", title: "Publish weekly content batch — Coastal Roofing", client: "coastal-roofing", due: "Mon", priority: "P1", status: "todo", category: "Content", assignee: "Niamh" },
    { id: "t4", title: "Launch Invisalign campaign — Atlantic Dental", client: "atlantic-dental", due: "Fri", priority: "P0", status: "doing", category: "Ads", assignee: "Bartek", objective: "o2" },
    { id: "t5", title: "Boyne Joinery — upsell to Growth tier", client: "boyne-joinery", due: "Wed", priority: "P1", status: "todo", category: "Sales", assignee: "Bartek", objective: "o1" },
    { id: "t6", title: "Weekly call · Murphy Plumbing", client: "murphy-plumbing", due: "Thu", priority: "P2", status: "todo", category: "Account", assignee: "Bartek" },
    { id: "t7", title: "Send review-request batch — Burke Landscaping", client: "burke-landscaping", due: "Tue", priority: "P2", status: "todo", category: "Reputation", assignee: "Auto" },
    { id: "t8", title: "QBR deck — O'Sullivan Electrical", client: "osullivan-electrical", due: "Next Tue", priority: "P1", status: "todo", category: "Account", assignee: "Bartek", objective: "o1" },
    { id: "t9", title: "Riverside Café — Christmas menu landing page", client: "riverside-cafe", due: "Thu", priority: "P2", status: "doing", category: "Web", assignee: "Niamh" },
    { id: "t10", title: "New starter onboarding video v2", client: null, due: "Fri", priority: "P2", status: "todo", category: "Internal", assignee: "Bartek" },
    { id: "t11", title: "Audit competitor — Greenway Fitness", client: "greenway-fitness", due: "Today", priority: "P0", status: "todo", category: "Strategy", assignee: "Bartek", objective: "o2" },
    { id: "t12", title: "Reply to Murphy 5★ reviews (8)", client: "murphy-plumbing", due: "Today", priority: "P2", status: "doing", category: "Reputation", assignee: "Auto" }
  ];

  const objectives = [
    {
      id: "o1",
      title: "Grow MRR to €15k/mo by end of Q3",
      owner: "Bartek",
      progress: 0.72,
      target: "€15k",
      current: "€7.8k",
      keyResults: [
        { kr: "Grow total MRR to €15k/mo", measure: "metric", metric: "mrr", startNum: 3000, targetNum: 15000, taskIds: [], checkpoints: [{ at: "2 weeks ago", value: "€5.8k", note: "Closed O'Sullivan on Domination — big jump." }] },
        { kr: "Upsell 3 Growth → Domination", measure: "tasks", taskIds: ["t5", "t8"], current: "1", target: "3", checkpoints: [] },
        { kr: "Reduce churn below 3%", measure: "manual", progress: 1.0, current: "2.1%", target: "<3%", checkpoints: [] }
      ]
    },
    {
      id: "o2",
      title: "Every client live & ranking inside 14 days",
      owner: "Bartek",
      progress: 0.81,
      target: "100% on-time",
      current: "8 / 9 inside 14d",
      keyResults: [
        { kr: "Average launch time < 7 days", progress: 0.9, current: "6.2d", target: "<7d" },
        { kr: "Day-14 leads landing for 100% clients", progress: 0.78, current: "7/9", target: "9/9" },
        { kr: "Onboarding NPS > 60", progress: 0.94, current: "72", target: ">60" }
      ]
    },
    {
      id: "o3",
      title: "Build out the Command Centre to replace Notion",
      owner: "Bartek",
      progress: 0.45,
      target: "v1.0 live",
      current: "v0.7",
      keyResults: [
        { kr: "Migrate all 9 clients off Notion", progress: 0.55, current: "5/9", target: "9/9" },
        { kr: "Ship master databases (Resources, Pages)", progress: 0.6, current: "2/3", target: "3/3" },
        { kr: "Integrations live: Meta, Google, Stripe", progress: 0.33, current: "1/3", target: "3/3" }
      ]
    }
  ];

  const activity = [
    { t: "2m", kind: "lead", client: "murphy-plumbing", msg: "New lead — emergency boiler, Salthill" },
    { t: "8m", kind: "review", client: "osullivan-electrical", msg: "★★★★★ review left by Sarah O'Brien" },
    { t: "14m", kind: "booking", client: "kelly-detailing", msg: "Booking confirmed — Ceramic coating · Sat" },
    { t: "23m", kind: "ad", client: "atlantic-dental", msg: "Ad set 'Invisalign-Sligo' hit 4.2 ROAS" },
    { t: "41m", kind: "missed", client: "greenway-fitness", msg: "Missed call auto-replied — booking pending" },
    { t: "1h", kind: "lead", client: "coastal-roofing", msg: "New lead — slate roof, Bandon" },
    { t: "1h", kind: "review", client: "riverside-cafe", msg: "★★★★★ Google review (32 this month)" },
    { t: "2h", kind: "booking", client: "burke-landscaping", msg: "Site survey booked — Castletroy" },
    { t: "3h", kind: "ai", client: null, msg: "AI: Greenway ad spend pacing 14% under target" },
    { t: "4h", kind: "lead", client: "kelly-detailing", msg: "New lead — full detail, Stillorgan" }
  ];

  const briefing = {
    date: "Mon · 25 May 2026",
    headline: "9 businesses · €7.8k MRR · 385 leads this month",
    wins: [
      { t: "O'Sullivan Electrical hit 7.2× ROAS — best month on record", client: "osullivan-electrical", metric: "roas",
        why: "The Search + PerfMax mix we rebuilt in April is compounding. Cost-per-lead fell while close rate held.", action: "Lock it in as a case study", actionKind: "task" },
      { t: "Kelly Detailing: +58% leads MoM since TikTok push", client: "kelly-detailing", metric: "leads",
        why: "Short-form video drove top-of-funnel hard. TikTok now out-performs Meta for this account on cost-per-lead.", action: "Scale TikTok budget +15%", actionKind: "task" },
      { t: "Riverside Café: 32 new 5★ reviews in 30 days", client: "riverside-cafe", metric: "reviews",
        why: "The post-visit review automation is firing perfectly — 41% of covers now leave a review.", action: "Roll the same flow to 2 more clients", actionKind: "task" }
    ],
    risks: [
      { t: "Greenway Fitness ROAS dropped to 2.4 — retention call today", client: "greenway-fitness", metric: "roas",
        why: "Ad fatigue on a stale creative set + a landing page that's converting at half the portfolio average. Health is down to 58.", action: "Book retention call + refresh creative", actionKind: "task", urgent: true },
      { t: "Boyne Joinery still on Starter — upsell call Wed", client: "boyne-joinery", metric: "plan",
        why: "Consistent demand on the free Starter tier — a textbook Growth upgrade. Leaving recurring revenue on the table.", action: "Run the upsell call Wednesday", actionKind: "task" },
      { t: "Kelly Detailing has 5 missed calls this week — chatbot misrouting", client: "kelly-detailing", metric: "missed",
        why: "The booking bot is mis-routing after-hours calls instead of texting back. Each miss is a lost job.", action: "Fix chatbot routing", actionKind: "task", urgent: true }
    ],
    today: [
      { t: "2 P0 tasks due", metric: "tasks", why: "Two urgent items are due today across the portfolio.", action: "Open today's tasks", actionKind: "tasks" },
      { t: "1 retention call (Greenway)", client: "greenway-fitness", metric: "call", why: "Greenway is at-risk — the retention call is the single highest-leverage thing you'll do today.", action: "Open Greenway", actionKind: "client" },
      { t: "Approve Kelly ad creative before 12:00", client: "kelly-detailing", metric: "ads", why: "New TikTok ad set is queued and waiting on your approval to go live before the lunchtime audience.", action: "Open Kelly", actionKind: "client" }
    ]
  };

  const integrations = [
    { id: "meta", name: "Meta / Facebook Ads", status: "connected", connectedTo: 8, color: "#1877F2", icon: "Ⓜ" },
    { id: "ga", name: "Google Analytics 4", status: "connected", connectedTo: 9, color: "#F9AB00", icon: "G" },
    { id: "gads", name: "Google Ads", status: "connected", connectedTo: 7, color: "#34A853", icon: "G" },
    { id: "gbp", name: "Google Business Profile", status: "connected", connectedTo: 9, color: "#4285F4", icon: "G" },
    { id: "ig", name: "Instagram", status: "connected", connectedTo: 9, color: "#E1306C", icon: "◉" },
    { id: "tt", name: "TikTok", status: "connected", connectedTo: 3, color: "#FE2C55", icon: "T" },
    { id: "stripe", name: "Stripe", status: "connected", connectedTo: 6, color: "#635BFF", icon: "S" },
    { id: "wa", name: "WhatsApp Business", status: "connected", connectedTo: 9, color: "#25D366", icon: "W" },
    { id: "cal", name: "Calendly", status: "partial", connectedTo: 4, color: "#006BFF", icon: "C" },
    { id: "hs", name: "HubSpot CRM", status: "disconnected", connectedTo: 0, color: "#FF7A59", icon: "H" }
  ];

  const resources = [
    { id: "r1", title: "Cold-call script · master v4.2", type: "Script", tag: "Sales", updated: "2d ago", owner: "Bartek", body: "INTRO (up tone, fast pace)\nHi [Name], it's Bartek from BizBoost — how's everything going today?\n\nI can see you've got great reviews and people love the service. Quick question — could you handle an extra 5 clients a month, or would that be too much?\n\nWe're Ireland's leading full-scale agency and we're finalising our last partnership spots for the year — taking just one [niche] business in [area].\n\nQUALIFY\n- What does your current process for getting clients look like?\n- When you get your perfect job, what does that look like?\n- What's the biggest thing slowing your growth?\n\nHOW IT WORKS\nStep 1: your own dashboard — the command centre for your business. Every lead, review, missed call and booking in real time, a lot of it handled automatically.\n\nCLOSE\nLet me lock you in for 30 minutes this week where I show you exactly what I'd build for you." },
    { id: "r2", title: "Meta ad creative — plumbing pack", type: "Creative", tag: "Ads", updated: "1d ago", owner: "Niamh", body: "Plumbing creative pack — 6 angles that consistently win:\n\n1. Emergency / urgency — \"Burst pipe? We're there in 60 mins.\"\n2. Trust / reviews — hero the 5★ count + a real testimonial.\n3. Before/after — leak → fixed, clean job photo.\n4. Offer — \"Free callout this week only.\"\n5. Local — \"Galway's most-booked plumber.\"\n6. Guarantee — \"Done right or we come back free.\"\n\nFormat: 1:1 + 9:16. Bold caption top-third, logo bottom-right, CTA \"Book in 30 seconds\"." },
    { id: "r3", title: "Website launch checklist", type: "SOP", tag: "Ops", updated: "1w ago", owner: "Bartek", body: "Pre-launch:\n- Domain connected + SSL live\n- Mobile pass (all breakpoints)\n- Booking widget tested end-to-end\n- Missed-call text-back wired\n- GA4 + Pixel firing\n- Google Business Profile linked\n- Reviews widget pulling live\n- Page speed > 90\n\nLaunch day:\n- DNS flip + cache clear\n- Submit sitemap\n- Test every form → lead lands\n- Confirm client login works\n\nPost-launch:\n- Day-7 performance check\n- First review-request batch sent" },
    { id: "r4", title: "Onboarding email sequence", type: "Sequence", tag: "Ops", updated: "3d ago", owner: "Auto" },
    { id: "r5", title: "Objection handling cheat sheet", type: "Doc", tag: "Sales", updated: "today", owner: "Bartek" },
    { id: "r6", title: "Review-request SMS templates", type: "Templates", tag: "Reputation", updated: "5d ago", owner: "Niamh" },
    { id: "r7", title: "QBR deck · master template", type: "Deck", tag: "Account", updated: "6d ago", owner: "Bartek" },
    { id: "r8", title: "Niche playbook · Trades", type: "Playbook", tag: "Strategy", updated: "2w ago", owner: "Bartek" },
    { id: "r9", title: "Niche playbook · Dental", type: "Playbook", tag: "Strategy", updated: "2w ago", owner: "Bartek" },
    { id: "r10", title: "Brand assets · logos & colour", type: "Brand", tag: "Brand", updated: "1mo ago", owner: "Bartek" }
  ];

  const pages = [
    { id: "p-coldcall", title: "BizBoost Cold Call Script", emoji: "📞", section: "Sales", updated: "just now" },
    { id: "p1", title: "How BizBoost actually works", emoji: "📘", section: "Wiki", updated: "3d ago" },
    { id: "p2", title: "Hiring rubric — closers", emoji: "🎯", section: "People", updated: "1w ago" },
    { id: "p3", title: "Pricing & guarantees", emoji: "💷", section: "Sales", updated: "4d ago" },
    { id: "p4", title: "Niche-specific FAQs", emoji: "❓", section: "Sales", updated: "2d ago" },
    { id: "p5", title: "Dashboard build spec — v1.0", emoji: "🛠", section: "Internal", updated: "today" },
    { id: "p6", title: "Founder log — Q2", emoji: "🪵", section: "Internal", updated: "yesterday" }
  ];

  // 6-month MRR trend
  const mrrTrend = [
    { m: "Dec", v: 38 },
    { m: "Jan", v: 44 },
    { m: "Feb", v: 51 },
    { m: "Mar", v: 58 },
    { m: "Apr", v: 64 },
    { m: "May", v: 72 }
  ];

  return { clients, tasks, objectives, activity, briefing, integrations, resources, pages, mrrTrend };
})();
