// BizBoost Command Centre — seed data (mirrors data-core.jsx)
import type { Client, Task, Objective, ActivityFeedItem, Resource, Page, Integration, Agent } from '@/types'

export const CLIENTS: Client[] = [
  {
    id: 'tobin-tiling',
    name: 'Tobin Tiling & Stone',
    handle: 'tobintiling.ie',
    city: 'Ennis',
    niche: 'Tiling',
    plan: 'Domination',
    mrr: 998,
    since: 'Jun 2026',
    onboarded: 2,
    health: 70,
    owner: 'Gerry Tobin',
    avatar: 'T',
    color: '#4FE3C1',
    leads30: 0,
    leads_delta: 0,
    bookings30: 0,
    bookings_delta: 0,
    revenue30: 0,
    revenue_delta: 0,
    roas: 0,
    missed_calls: 0,
    reviews_count: 0,
    reviews_rating: 0,
    reviews_new30: 0,
    ad_spend: 0,
    website_visits30: 0,
    website_visits_delta: 0,
    website_conv: 0,
    followers_ig: 0,
    followers_fb: 0,
    followers_tt: 0,
    pending_tasks: 5,
    last_touch: 'today',
    next_due: 'Onboarding',
    flag: 'Onboarding',
    services: ['Bathroom tiling', 'Natural stone', 'Wet rooms'],
    sparkline: [0, 0, 0, 0, 0],
    connected: ['meta', 'gbp'],
    memory: {
      why: '20 years on the tools, obsessive about a clean grout line — does the jobs cowboys won\'t touch.',
      ideal: 'Full bathroom & wet-room renovations for homeowners who care about finish, €6k+ jobs.',
      vibe: 'Premium & clean',
      competitor: 'Clare Tile Co',
    },
    onboarding_active: true,
    onboarding_done: ['k1', 'k2'],
    onboarding_started: '2 days ago',
    created_at: new Date().toISOString(),
  },
  {
    id: 'murphy-plumbing',
    name: 'Murphy & Sons Plumbing',
    handle: 'murphyplumbing.ie',
    city: 'Galway',
    niche: 'Plumbing',
    plan: 'Domination',
    mrr: 998,
    since: 'Jan 2026',
    onboarded: 142,
    health: 92,
    owner: 'Liam Murphy',
    avatar: 'M',
    color: '#3FE0A8',
    leads30: 47,
    leads_delta: 0.32,
    bookings30: 31,
    bookings_delta: 0.18,
    revenue30: 28400,
    revenue_delta: 0.21,
    roas: 6.4,
    missed_calls: 2,
    reviews_count: 187,
    reviews_rating: 4.9,
    reviews_new30: 22,
    ad_spend: 2400,
    website_visits30: 8120,
    website_visits_delta: 0.41,
    website_conv: 4.2,
    followers_ig: 2840,
    followers_fb: 1620,
    followers_tt: 0,
    pending_tasks: 3,
    last_touch: '2h ago',
    next_due: 'Weekly call · Thu',
    flag: null,
    services: ['Emergency callouts', 'Boiler install', 'Bathroom fitouts'],
    sparkline: [12, 14, 11, 18, 21, 19, 24, 22, 26, 29, 31, 35, 38, 41, 47],
    connected: ['meta', 'ga', 'gbp', 'ig'],
    memory: {
      why: 'Family business since 1989, Liam took over in 2018. Best emergency response in Connacht.',
      ideal: 'Homeowners with boiler emergencies + bathroom fitout projects, €800–€15k jobs.',
      vibe: 'Trustworthy & local',
      competitor: 'Galway Plumbing Co',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'coastal-roofing',
    name: 'Coastal Roofing Ltd',
    handle: 'coastalroofing.ie',
    city: 'Cork',
    niche: 'Roofing',
    plan: 'Domination',
    mrr: 998,
    since: 'Nov 2025',
    onboarded: 198,
    health: 88,
    owner: 'Declan Walsh',
    avatar: 'C',
    color: '#CFFF3A',
    leads30: 39,
    leads_delta: 0.12,
    bookings30: 22,
    bookings_delta: 0.04,
    revenue30: 41200,
    revenue_delta: 0.09,
    roas: 5.1,
    missed_calls: 0,
    reviews_count: 96,
    reviews_rating: 4.8,
    reviews_new30: 11,
    ad_spend: 3100,
    website_visits30: 5240,
    website_visits_delta: 0.18,
    website_conv: 5.8,
    followers_ig: 1840,
    followers_fb: 2210,
    followers_tt: 410,
    pending_tasks: 1,
    last_touch: 'yesterday',
    next_due: 'Content batch · Mon',
    flag: null,
    services: ['Slate roofing', 'Flat roofs', 'Gutter repair'],
    sparkline: [22, 26, 24, 28, 31, 29, 33, 30, 34, 32, 35, 38, 36, 39, 39],
    connected: ['meta', 'ga', 'gbp', 'ig', 'gads'],
    memory: {
      why: 'Third-generation roofers, only team in Munster certified for natural slate.',
      ideal: 'Homeowners doing full re-roofing + commercial flat roofs, €4k–€40k jobs.',
      vibe: 'Expert & reliable',
      competitor: 'Cork Roofing Masters',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'kelly-detailing',
    name: 'Kelly Auto Detailing',
    handle: 'kellydetailing.ie',
    city: 'Dublin',
    niche: 'Auto Detailing',
    plan: 'Growth',
    mrr: 698,
    since: 'Mar 2026',
    onboarded: 78,
    health: 71,
    owner: 'Aoife Kelly',
    avatar: 'K',
    color: '#FFB547',
    leads30: 84,
    leads_delta: 0.58,
    bookings30: 51,
    bookings_delta: 0.44,
    revenue30: 16800,
    revenue_delta: 0.39,
    roas: 4.2,
    missed_calls: 5,
    reviews_count: 64,
    reviews_rating: 4.7,
    reviews_new30: 18,
    ad_spend: 1800,
    website_visits30: 11200,
    website_visits_delta: 0.62,
    website_conv: 3.1,
    followers_ig: 6210,
    followers_fb: 980,
    followers_tt: 14200,
    pending_tasks: 6,
    last_touch: '3d ago',
    next_due: 'Ads review · today',
    flag: 'Needs ad approval',
    services: ['Full detail', 'Ceramic coating', 'Headlight restoration'],
    sparkline: [18, 22, 31, 28, 36, 42, 48, 51, 58, 63, 68, 72, 76, 80, 84],
    connected: ['meta', 'ig', 'tt'],
    memory: {
      why: 'Aoife left a corporate job to pursue her passion for cars. First female-run detailing studio in Leinster.',
      ideal: 'Car enthusiasts aged 25–45 with prestige/sports cars, €300–€2,000 jobs.',
      vibe: 'Aspirational & premium',
      competitor: 'Dublin Auto Spa',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'burke-landscaping',
    name: 'Burke Landscaping',
    handle: 'burkelandscapes.ie',
    city: 'Limerick',
    niche: 'Landscaping',
    plan: 'Growth',
    mrr: 698,
    since: 'Feb 2026',
    onboarded: 102,
    health: 84,
    owner: 'Seán Burke',
    avatar: 'B',
    color: '#4FE3C1',
    leads30: 28,
    leads_delta: 0.08,
    bookings30: 19,
    bookings_delta: 0.11,
    revenue30: 22600,
    revenue_delta: 0.14,
    roas: 5.8,
    missed_calls: 1,
    reviews_count: 41,
    reviews_rating: 4.9,
    reviews_new30: 8,
    ad_spend: 1200,
    website_visits30: 3210,
    website_visits_delta: 0.09,
    website_conv: 4.8,
    followers_ig: 1240,
    followers_fb: 760,
    followers_tt: 0,
    pending_tasks: 2,
    last_touch: '5h ago',
    next_due: 'Review request batch',
    flag: null,
    services: ['Garden design', 'Turf laying', 'Maintenance'],
    sparkline: [18, 19, 22, 20, 24, 23, 26, 24, 27, 25, 28, 26, 29, 27, 28],
    connected: ['meta', 'gbp', 'ig'],
    memory: {
      why: 'Seán is a horticulture graduate who turned a van and a lawnmower into a 6-man crew in 3 years.',
      ideal: 'Homeowners wanting full garden redesigns + regular maintenance contracts, €1k–€15k.',
      vibe: 'Friendly expert',
      competitor: 'Limerick Lawns',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'boyne-joinery',
    name: 'Boyne Valley Joinery',
    handle: 'boynejoinery.ie',
    city: 'Drogheda',
    niche: 'Joinery',
    plan: 'Starter',
    mrr: 0,
    since: 'Apr 2026',
    onboarded: 41,
    health: 64,
    owner: 'Tomás Reilly',
    avatar: 'B',
    color: '#8B7CFF',
    leads30: 14,
    leads_delta: -0.04,
    bookings30: 9,
    bookings_delta: 0.02,
    revenue30: 11400,
    revenue_delta: 0.06,
    roas: 3.8,
    missed_calls: 3,
    reviews_count: 22,
    reviews_rating: 4.6,
    reviews_new30: 4,
    ad_spend: 600,
    website_visits30: 1840,
    website_visits_delta: -0.02,
    website_conv: 3.4,
    followers_ig: 480,
    followers_fb: 320,
    followers_tt: 0,
    pending_tasks: 4,
    last_touch: '6d ago',
    next_due: 'Upsell call · Wed',
    flag: 'Upsell opportunity',
    services: ['Bespoke kitchens', 'Staircases', 'Wardrobes'],
    sparkline: [10, 11, 12, 10, 13, 11, 14, 12, 14, 13, 13, 14, 14, 14, 14],
    connected: ['gbp'],
    memory: {
      why: 'Tomás is a 4th-generation joiner. Every piece is handmade — no MDF, no shortcuts.',
      ideal: 'Self-build and renovation homeowners who want bespoke fitted furniture, €3k–€20k.',
      vibe: 'Craft & heritage',
      competitor: 'Louth Kitchens',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'osullivan-electrical',
    name: "O'Sullivan Electrical",
    handle: 'osullivanelectric.ie',
    city: 'Waterford',
    niche: 'Electrical',
    plan: 'Domination',
    mrr: 998,
    since: 'Sep 2025',
    onboarded: 248,
    health: 95,
    owner: "Mick O'Sullivan",
    avatar: 'O',
    color: '#FF7A8A',
    leads30: 61,
    leads_delta: 0.22,
    bookings30: 44,
    bookings_delta: 0.19,
    revenue30: 38200,
    revenue_delta: 0.16,
    roas: 7.2,
    missed_calls: 0,
    reviews_count: 312,
    reviews_rating: 4.95,
    reviews_new30: 28,
    ad_spend: 2200,
    website_visits30: 9420,
    website_visits_delta: 0.24,
    website_conv: 5.4,
    followers_ig: 1980,
    followers_fb: 3400,
    followers_tt: 0,
    pending_tasks: 0,
    last_touch: 'today',
    next_due: 'QBR · next Tue',
    flag: 'Top performer',
    services: ['EV chargers', 'Rewiring', 'Commercial fitouts'],
    sparkline: [42, 45, 48, 44, 51, 53, 57, 55, 59, 58, 60, 59, 61, 61, 61],
    connected: ['meta', 'ga', 'gbp', 'ig', 'gads', 'stripe'],
    memory: {
      why: "Mick is Waterford's most-reviewed electrician — 312 Google reviews, nearly all 5★.",
      ideal: 'Homeowners needing EV charger installation + rewiring + commercial clients, €500–€25k.',
      vibe: 'Professional & modern',
      competitor: 'Waterford Electrical',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'atlantic-dental',
    name: 'Atlantic Dental Clinic',
    handle: 'atlanticdental.ie',
    city: 'Sligo',
    niche: 'Dental',
    plan: 'Domination',
    mrr: 998,
    since: 'Dec 2025',
    onboarded: 168,
    health: 81,
    owner: 'Dr. Niamh O\'Connor',
    avatar: 'A',
    color: '#5BCEFA',
    leads30: 52,
    leads_delta: 0.14,
    bookings30: 38,
    bookings_delta: 0.21,
    revenue30: 47800,
    revenue_delta: 0.12,
    roas: 5.6,
    missed_calls: 1,
    reviews_count: 142,
    reviews_rating: 4.85,
    reviews_new30: 14,
    ad_spend: 2800,
    website_visits30: 6420,
    website_visits_delta: 0.07,
    website_conv: 5.1,
    followers_ig: 3210,
    followers_fb: 1820,
    followers_tt: 0,
    pending_tasks: 2,
    last_touch: '1d ago',
    next_due: 'Campaign launch · Fri',
    flag: null,
    services: ['Invisalign', 'Implants', 'Hygiene'],
    sparkline: [38, 40, 42, 41, 44, 43, 46, 45, 47, 46, 48, 48, 50, 51, 52],
    connected: ['meta', 'ga', 'gbp', 'ig', 'gads'],
    memory: {
      why: 'Dr O\'Connor opened Atlantic Dental in 2019, built it to the largest practice in Connacht.',
      ideal: 'Patients seeking Invisalign, implants and cosmetic work, €500–€8k treatment plans.',
      vibe: 'Clinical excellence',
      competitor: 'Sligo Dental Centre',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'greenway-fitness',
    name: 'Greenway Fitness',
    handle: 'greenwayfit.ie',
    city: 'Kildare',
    niche: 'Fitness Studio',
    plan: 'Growth',
    mrr: 698,
    since: 'Feb 2026',
    onboarded: 108,
    health: 58,
    owner: 'Conor Doyle',
    avatar: 'G',
    color: '#FF6B5C',
    leads30: 22,
    leads_delta: -0.18,
    bookings30: 11,
    bookings_delta: -0.24,
    revenue30: 7400,
    revenue_delta: -0.12,
    roas: 2.4,
    missed_calls: 7,
    reviews_count: 38,
    reviews_rating: 4.5,
    reviews_new30: 2,
    ad_spend: 1400,
    website_visits30: 4210,
    website_visits_delta: -0.08,
    website_conv: 2.1,
    followers_ig: 1820,
    followers_fb: 410,
    followers_tt: 980,
    pending_tasks: 8,
    last_touch: '8d ago',
    next_due: 'Retention call · today',
    flag: 'At risk',
    services: ['6-week challenge', 'Personal training', 'Group classes'],
    sparkline: [28, 26, 24, 28, 22, 25, 22, 20, 21, 19, 22, 20, 22, 22, 22],
    connected: ['meta', 'ig'],
    memory: {
      why: 'Conor opened Greenway after competing as an amateur boxer for 10 years. Transformation focus.',
      ideal: 'Adults 28–45 looking for structured transformation programmes, €200–€1,000.',
      vibe: 'Motivational & community',
      competitor: 'Kildare Fitness Hub',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'riverside-cafe',
    name: 'Riverside Café',
    handle: 'riversidecafe.ie',
    city: 'Kilkenny',
    niche: 'Hospitality',
    plan: 'Growth',
    mrr: 698,
    since: 'Mar 2026',
    onboarded: 84,
    health: 78,
    owner: 'Orla Hennessy',
    avatar: 'R',
    color: '#FFD66B',
    leads30: 38,
    leads_delta: 0.28,
    bookings30: 0,
    bookings_delta: 0,
    revenue30: 18900,
    revenue_delta: 0.18,
    roas: 0,
    missed_calls: 0,
    reviews_count: 218,
    reviews_rating: 4.7,
    reviews_new30: 32,
    ad_spend: 800,
    website_visits30: 7820,
    website_visits_delta: 0.34,
    website_conv: 0,
    followers_ig: 8420,
    followers_fb: 2240,
    followers_tt: 4120,
    pending_tasks: 2,
    last_touch: 'today',
    next_due: 'Content batch · Thu',
    flag: null,
    services: ['Brunch', 'Events', 'Private hire'],
    sparkline: [24, 26, 28, 30, 31, 30, 33, 32, 34, 35, 36, 36, 37, 37, 38],
    connected: ['meta', 'ig', 'tt', 'gbp'],
    memory: {
      why: "Orla converted a riverside warehouse into Kilkenny's most Instagrammed brunch spot.",
      ideal: 'Brunch customers, event bookings, corporate private hire, €20–€2,000.',
      vibe: 'Warm & aesthetic',
      competitor: 'The Yard Kitchen',
    },
    onboarding_active: false,
    onboarding_done: [],
    onboarding_started: null,
    created_at: new Date().toISOString(),
  },
]

export const TASKS: Task[] = [
  { id: 't1', title: 'Approve Q4 ad creative — Kelly Detailing', description: null, client_id: 'kelly-detailing', due_date: 'Today', priority: 'P0', status: 'doing', category: 'Ads', assignee: 'Bartek', objective_id: null, archived: false, created_at: new Date().toISOString() },
  { id: 't2', title: 'Greenway Fitness retention call', description: null, client_id: 'greenway-fitness', due_date: 'Today', priority: 'P0', status: 'todo', category: 'Account', assignee: 'Bartek', objective_id: null, archived: false, created_at: new Date().toISOString() },
  { id: 't3', title: 'Publish weekly content batch — Coastal Roofing', description: null, client_id: 'coastal-roofing', due_date: 'Mon', priority: 'P1', status: 'todo', category: 'Content', assignee: 'Niamh', objective_id: null, archived: false, created_at: new Date().toISOString() },
  { id: 't4', title: 'Launch Invisalign campaign — Atlantic Dental', description: null, client_id: 'atlantic-dental', due_date: 'Fri', priority: 'P0', status: 'doing', category: 'Ads', assignee: 'Bartek', objective_id: 'o2', archived: false, created_at: new Date().toISOString() },
  { id: 't5', title: 'Boyne Joinery — upsell to Growth tier', description: null, client_id: 'boyne-joinery', due_date: 'Wed', priority: 'P1', status: 'todo', category: 'Sales', assignee: 'Bartek', objective_id: 'o1', archived: false, created_at: new Date().toISOString() },
  { id: 't6', title: 'Weekly call · Murphy Plumbing', description: null, client_id: 'murphy-plumbing', due_date: 'Thu', priority: 'P2', status: 'todo', category: 'Account', assignee: 'Bartek', objective_id: null, archived: false, created_at: new Date().toISOString() },
  { id: 't7', title: 'Send review-request batch — Burke Landscaping', description: null, client_id: 'burke-landscaping', due_date: 'Tue', priority: 'P2', status: 'todo', category: 'Reputation', assignee: 'Auto', objective_id: null, archived: false, created_at: new Date().toISOString() },
  { id: 't8', title: "QBR deck — O'Sullivan Electrical", description: null, client_id: 'osullivan-electrical', due_date: 'Next Tue', priority: 'P1', status: 'todo', category: 'Account', assignee: 'Bartek', objective_id: 'o1', archived: false, created_at: new Date().toISOString() },
  { id: 't9', title: 'Riverside Café — Christmas menu landing page', description: null, client_id: 'riverside-cafe', due_date: 'Thu', priority: 'P2', status: 'doing', category: 'Web', assignee: 'Niamh', objective_id: null, archived: false, created_at: new Date().toISOString() },
  { id: 't10', title: 'New starter onboarding video v2', description: null, client_id: null, due_date: 'Fri', priority: 'P2', status: 'todo', category: 'Internal', assignee: 'Bartek', objective_id: null, archived: false, created_at: new Date().toISOString() },
  { id: 't11', title: 'Audit competitor — Greenway Fitness', description: null, client_id: 'greenway-fitness', due_date: 'Today', priority: 'P0', status: 'todo', category: 'Strategy', assignee: 'Bartek', objective_id: 'o2', archived: false, created_at: new Date().toISOString() },
  { id: 't12', title: 'Reply to Murphy 5★ reviews (8)', description: null, client_id: 'murphy-plumbing', due_date: 'Today', priority: 'P2', status: 'doing', category: 'Reputation', assignee: 'Auto', objective_id: null, archived: false, created_at: new Date().toISOString() },
]

export const OBJECTIVES: Objective[] = [
  {
    id: 'o1',
    title: 'Grow MRR to €15k/mo by end of Q3',
    owner: 'Bartek',
    current_value: 7800,
    target_value: 15000,
    progress: 0.72,
    progress_mode: 'krs',
    key_results: [
      { kr: 'Grow total MRR to €15k/mo', measure: 'metric', metric: 'mrr', start_num: 3000, target_num: 15000, task_ids: [], checkpoints: [{ at: '2 weeks ago', value: '€5.8k', note: 'Closed O\'Sullivan on Domination — big jump.' }] },
      { kr: 'Upsell 3 Growth → Domination', measure: 'tasks', task_ids: ['t5', 't8'], current: '1', target: '3', checkpoints: [] },
      { kr: 'Reduce churn below 3%', measure: 'manual', progress: 1.0, current: '2.1%', target: '<3%', checkpoints: [] },
    ],
    linked_tasks: ['t5', 't8'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'o2',
    title: 'Every client live & ranking inside 14 days',
    owner: 'Bartek',
    current_value: 8,
    target_value: 9,
    progress: 0.81,
    progress_mode: 'krs',
    key_results: [
      { kr: 'Average launch time < 7 days', measure: 'manual', progress: 0.9, current: '6.2d', target: '<7d' },
      { kr: 'Day-14 leads landing for 100% clients', measure: 'manual', progress: 0.78, current: '7/9', target: '9/9' },
      { kr: 'Onboarding NPS > 60', measure: 'manual', progress: 0.94, current: '72', target: '>60' },
    ],
    linked_tasks: ['t4', 't11'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'o3',
    title: 'Build out the Command Centre to replace Notion',
    owner: 'Bartek',
    current_value: 5,
    target_value: 9,
    progress: 0.45,
    progress_mode: 'krs',
    key_results: [
      { kr: 'Migrate all 9 clients off Notion', measure: 'manual', progress: 0.55, current: '5/9', target: '9/9' },
      { kr: 'Ship master databases (Resources, Pages)', measure: 'manual', progress: 0.6, current: '2/3', target: '3/3' },
      { kr: 'Integrations live: Meta, Google, Stripe', measure: 'manual', progress: 0.33, current: '1/3', target: '3/3' },
    ],
    linked_tasks: [],
    created_at: new Date().toISOString(),
  },
]

export const ACTIVITY: ActivityFeedItem[] = [
  { id: 'a1', type: 'lead', client_id: 'murphy-plumbing', message: 'New lead — emergency boiler, Salthill', metadata: null, created_at: new Date(Date.now() - 2 * 60000).toISOString() },
  { id: 'a2', type: 'review', client_id: 'osullivan-electrical', message: "★★★★★ review left by Sarah O'Brien", metadata: null, created_at: new Date(Date.now() - 8 * 60000).toISOString() },
  { id: 'a3', type: 'booking', client_id: 'kelly-detailing', message: 'Booking confirmed — Ceramic coating · Sat', metadata: null, created_at: new Date(Date.now() - 14 * 60000).toISOString() },
  { id: 'a4', type: 'ad', client_id: 'atlantic-dental', message: "Ad set 'Invisalign-Sligo' hit 4.2 ROAS", metadata: null, created_at: new Date(Date.now() - 23 * 60000).toISOString() },
  { id: 'a5', type: 'missed', client_id: 'greenway-fitness', message: 'Missed call auto-replied — booking pending', metadata: null, created_at: new Date(Date.now() - 41 * 60000).toISOString() },
  { id: 'a6', type: 'lead', client_id: 'coastal-roofing', message: 'New lead — slate roof, Bandon', metadata: null, created_at: new Date(Date.now() - 60 * 60000).toISOString() },
  { id: 'a7', type: 'review', client_id: 'riverside-cafe', message: '★★★★★ Google review (32 this month)', metadata: null, created_at: new Date(Date.now() - 65 * 60000).toISOString() },
  { id: 'a8', type: 'booking', client_id: 'burke-landscaping', message: 'Site survey booked — Castletroy', metadata: null, created_at: new Date(Date.now() - 120 * 60000).toISOString() },
  { id: 'a9', type: 'ai', client_id: null, message: 'AI: Greenway ad spend pacing 14% under target', metadata: null, created_at: new Date(Date.now() - 180 * 60000).toISOString() },
  { id: 'a10', type: 'lead', client_id: 'kelly-detailing', message: 'New lead — full detail, Stillorgan', metadata: null, created_at: new Date(Date.now() - 240 * 60000).toISOString() },
]

export const MRR_TREND = [
  { m: 'Dec', v: 38 },
  { m: 'Jan', v: 44 },
  { m: 'Feb', v: 51 },
  { m: 'Mar', v: 58 },
  { m: 'Apr', v: 64 },
  { m: 'May', v: 72 },
]

export const RESOURCES: Resource[] = [
  { id: 'r1', title: 'Cold-call script · master v4.2', type: 'Script', tag: 'Sales', body: "INTRO (up tone, fast pace)\nHi [Name], it's Bartek from BizBoost — how's everything going today?\n\nI can see you've got great reviews and people love the service. Quick question — could you handle an extra 5 clients a month, or would that be too much?\n\nQUALIFY\n- What does your current process for getting clients look like?\n- When you get your perfect job, what does that look like?\n- What's the biggest thing slowing your growth?\n\nHOW IT WORKS\nStep 1: your own dashboard — the command centre for your business. Every lead, review, missed call and booking in real time, a lot of it handled automatically.\n\nCLOSE\nLet me lock you in for 30 minutes this week where I show you exactly what I'd build for you.", created_at: new Date().toISOString() },
  { id: 'r2', title: 'Meta ad creative — plumbing pack', type: 'Creative', tag: 'Ads', body: "Plumbing creative pack — 6 angles:\n1. Emergency/urgency — \"Burst pipe? We're there in 60 mins.\"\n2. Trust/reviews — hero the 5★ count.\n3. Before/after — leak → fixed, clean job photo.\n4. Offer — \"Free callout this week only.\"\n5. Local — \"Galway's most-booked plumber.\"\n6. Guarantee — \"Done right or we come back free.\"", created_at: new Date().toISOString() },
  { id: 'r3', title: 'Website launch checklist', type: 'SOP', tag: 'Ops', body: "Pre-launch:\n- Domain connected + SSL live\n- Mobile pass (all breakpoints)\n- Booking widget tested end-to-end\n- Missed-call text-back wired\n- GA4 + Pixel firing\n- Google Business Profile linked\n- Reviews widget pulling live\n- Page speed > 90\n\nLaunch day:\n- DNS flip + cache clear\n- Submit sitemap\n- Test every form → lead lands\n\nPost-launch:\n- Day-7 performance check\n- First review-request batch sent", created_at: new Date().toISOString() },
  { id: 'r4', title: 'Onboarding email sequence', type: 'Sequence', tag: 'Ops', body: null, created_at: new Date().toISOString() },
  { id: 'r5', title: 'Objection handling cheat sheet', type: 'Doc', tag: 'Sales', body: null, created_at: new Date().toISOString() },
  { id: 'r6', title: 'Review-request SMS templates', type: 'Templates', tag: 'Reputation', body: null, created_at: new Date().toISOString() },
  { id: 'r7', title: 'QBR deck · master template', type: 'Deck', tag: 'Account', body: null, created_at: new Date().toISOString() },
  { id: 'r8', title: 'Niche playbook · Trades', type: 'Playbook', tag: 'Strategy', body: null, created_at: new Date().toISOString() },
  { id: 'r9', title: 'Niche playbook · Dental', type: 'Playbook', tag: 'Strategy', body: null, created_at: new Date().toISOString() },
  { id: 'r10', title: 'Brand assets · logos & colour', type: 'Brand', tag: 'Brand', body: null, created_at: new Date().toISOString() },
]

export const PAGES: Page[] = [
  { id: 'p-coldcall', title: 'BizBoost Cold Call Script', parent_id: null, content_blocks: [], theme: 'dark', tags: ['Sales'], icon: '📞', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'p1', title: 'How BizBoost actually works', parent_id: null, content_blocks: [], theme: 'dark', tags: ['Wiki'], icon: '📘', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'p2', title: 'Hiring rubric — closers', parent_id: null, content_blocks: [], theme: 'dark', tags: ['People'], icon: '🎯', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'p3', title: 'Pricing & guarantees', parent_id: null, content_blocks: [], theme: 'dark', tags: ['Sales'], icon: '💷', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'p4', title: 'Niche-specific FAQs', parent_id: null, content_blocks: [], theme: 'dark', tags: ['Sales'], icon: '❓', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'p5', title: 'Dashboard build spec — v1.0', parent_id: null, content_blocks: [], theme: 'dark', tags: ['Internal'], icon: '🛠', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'p6', title: 'Founder log — Q2', parent_id: null, content_blocks: [], theme: 'dark', tags: ['Internal'], icon: '🪵', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
]

export const INTEGRATIONS_DATA = [
  { id: 'meta', name: 'Meta / Facebook Ads', status: 'connected', connectedTo: 8, color: '#1877F2', icon: 'Ⓜ' },
  { id: 'ga', name: 'Google Analytics 4', status: 'connected', connectedTo: 9, color: '#F9AB00', icon: 'G' },
  { id: 'gads', name: 'Google Ads', status: 'connected', connectedTo: 7, color: '#34A853', icon: 'G' },
  { id: 'gbp', name: 'Google Business Profile', status: 'connected', connectedTo: 9, color: '#4285F4', icon: 'G' },
  { id: 'ig', name: 'Instagram', status: 'connected', connectedTo: 9, color: '#E1306C', icon: '◉' },
  { id: 'tt', name: 'TikTok', status: 'connected', connectedTo: 3, color: '#FE2C55', icon: 'T' },
  { id: 'stripe', name: 'Stripe', status: 'connected', connectedTo: 6, color: '#635BFF', icon: 'S' },
  { id: 'wa', name: 'WhatsApp Business', status: 'connected', connectedTo: 9, color: '#25D366', icon: 'W' },
  { id: 'cal', name: 'Calendly', status: 'partial', connectedTo: 4, color: '#006BFF', icon: 'C' },
  { id: 'hs', name: 'HubSpot CRM', status: 'disconnected', connectedTo: 0, color: '#FF7A59', icon: 'H' },
]

export const AGENTS_DATA: Agent[] = [
  { id: 'ag1', name: 'Boost', role: 'Chief AI officer', type: 'ai', tools: ['All pages', 'Write tasks', 'Draft briefs'], capabilities: 'Strategic analysis, briefings, coaching, data interpretation', status: 'idle', run_count: 847, avatar: '⚡', is_active: true, created_at: new Date().toISOString() },
  { id: 'ag2', name: 'Research Agent', role: 'Lead intelligence', type: 'ai', tools: ['Google', 'Meta Ad Library', 'GMB'], capabilities: 'Deep-dives leads, audits competitors, builds meeting briefs', status: 'running', run_count: 214, avatar: '🔍', is_active: true, created_at: new Date().toISOString() },
  { id: 'ag3', name: 'Review Responder', role: 'Reputation manager', type: 'ai', tools: ['Google API', 'WhatsApp'], capabilities: 'Auto-responds to Google reviews, flags anything < 4★', status: 'idle', run_count: 1240, avatar: '⭐', is_active: true, created_at: new Date().toISOString() },
  { id: 'ag4', name: 'Missed Call Handler', role: 'Lead recovery', type: 'ai', tools: ['SMS', 'Calendly', 'CRM'], capabilities: 'Texts back within 60s, books the lead into next available slot', status: 'idle', run_count: 388, avatar: '📱', is_active: true, created_at: new Date().toISOString() },
]

export const BRIEFING = {
  date: 'Mon · 25 May 2026',
  headline: '9 businesses · €7.8k MRR · 385 leads this month',
  wins: [
    { t: "O'Sullivan Electrical hit 7.2× ROAS — best month on record", client: 'osullivan-electrical', metric: 'roas', why: 'The Search + PerfMax mix we rebuilt in April is compounding. Cost-per-lead fell while close rate held.', action: 'Lock it in as a case study', actionKind: 'task' },
    { t: 'Kelly Detailing: +58% leads MoM since TikTok push', client: 'kelly-detailing', metric: 'leads', why: 'Short-form video drove top-of-funnel hard. TikTok now out-performs Meta for this account on cost-per-lead.', action: 'Scale TikTok budget +15%', actionKind: 'task' },
    { t: 'Riverside Café: 32 new 5★ reviews in 30 days', client: 'riverside-cafe', metric: 'reviews', why: 'The post-visit review automation is firing perfectly — 41% of covers now leave a review.', action: 'Roll the same flow to 2 more clients', actionKind: 'task' },
  ],
  risks: [
    { t: 'Greenway Fitness ROAS dropped to 2.4 — retention call today', client: 'greenway-fitness', metric: 'roas', why: 'Ad fatigue on a stale creative set + a landing page that\'s converting at half the portfolio average. Health is down to 58.', action: 'Book retention call + refresh creative', actionKind: 'task', urgent: true },
    { t: 'Boyne Joinery still on Starter — upsell call Wed', client: 'boyne-joinery', metric: 'plan', why: 'Consistent demand on the free Starter tier — a textbook Growth upgrade. Leaving recurring revenue on the table.', action: 'Run the upsell call Wednesday', actionKind: 'task' },
    { t: 'Kelly Detailing has 5 missed calls this week — chatbot misrouting', client: 'kelly-detailing', metric: 'missed', why: 'The booking bot is mis-routing after-hours calls instead of texting back. Each miss is a lost job.', action: 'Fix chatbot routing', actionKind: 'task', urgent: true },
  ],
  today: [
    { t: '2 P0 tasks due', metric: 'tasks', why: 'Two urgent items are due today across the portfolio.', action: "Open today's tasks", actionKind: 'tasks' },
    { t: '1 retention call (Greenway)', client: 'greenway-fitness', metric: 'call', why: 'Greenway is at-risk — the retention call is the single highest-leverage thing you\'ll do today.', action: 'Open Greenway', actionKind: 'client' },
    { t: 'Approve Kelly ad creative before 12:00', client: 'kelly-detailing', metric: 'ads', why: 'New TikTok ad set is queued and waiting on your approval to go live before the lunchtime audience.', action: 'Open Kelly', actionKind: 'client' },
  ],
}

export const LEADS_DATA = {
  stages: [
    { id: 'new', label: 'New lead', color: '#5BCEFA' },
    { id: 'contacted', label: 'Contacted', color: '#8B7CFF' },
    { id: 'meeting', label: 'Meeting booked', color: '#FFB347' },
    { id: 'researching', label: 'Researching', color: '#CFFF3A' },
    { id: 'proposal', label: 'Proposal sent', color: '#4FE3C1' },
    { id: 'won', label: 'Closed', color: '#3FE0A8' },
    { id: 'lost', label: 'Lost', color: '#FF5F5F' },
  ],
  leads: [
    { id: 'l1', business: 'Premier Plumbing', person: 'Padraig Connolly', niche: 'Plumbing', area: 'Dublin 4', stage: 'meeting', research: 'complete', meetingAt: 'Wed ·2pm', meetingIn: 'tomorrow', value: 12000, color: '#5BCEFA', introSent: true, priority: 1 },
    { id: 'l2', business: 'Shine Window Cleaning', person: 'Claire Murphy', niche: 'Cleaning', area: 'Cork City', stage: 'researching', research: 'running', meetingAt: 'Thu · 11am', meetingIn: '2 days', value: 8500, color: '#8B7CFF', introSent: true, priority: 2 },
    { id: 'l3', business: 'Egan Security Systems', person: 'Martin Egan', niche: 'Security', area: 'Limerick', stage: 'new', research: 'queued', meetingAt: 'Not set', meetingIn: 'TBC', value: 9800, color: '#FFB347', introSent: false, priority: 3 },
    { id: 'l4', business: 'Galway Bay Removals', person: 'Sinéad Walsh', niche: 'Removals', area: 'Galway', stage: 'contacted', research: 'queued', meetingAt: 'Fri · 10am', meetingIn: '3 days', value: 7200, color: '#4FE3C1', introSent: true, priority: 4 },
    { id: 'l5', business: 'Munster Skip Hire', person: 'Brendan Lyons', niche: 'Waste', area: 'Tipperary', stage: 'proposal', research: 'complete', meetingAt: 'done', meetingIn: 'done', value: 14400, color: '#CFFF3A', introSent: true, priority: 5 },
  ],
}

export function getClient(id: string): Client | undefined {
  return CLIENTS.find(c => c.id === id)
}
